services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:8880"
      - "--entrypoints.websecure.address=:8443"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "8880:8880"
      - "8443:8443"
      - "8081:8080"   # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dynamic:/etc/traefik/dynamic
    networks: [usewa-net]

  postgres:
    image: postgres:16-alpine
    env_file: ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [usewa-net]

  redis:
    image: redis:7-alpine
    networks: [usewa-net]

  auth-service:
    build:
      context: ../services/auth-service
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=4000"
    networks: [usewa-net]

  catalog-service:
    build:
      context: ../services/catalog-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.catalog.rule=PathPrefix(`/catalog`)"
      - "traefik.http.services.catalog.loadbalancer.server.port=4000"
    networks: [usewa-net]

  orders-service:
    build:
      context: ../services/orders-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.orders.loadbalancer.server.port=4000"
    networks: [usewa-net]

  notifications-service:
    build:
      context: ../services/notifications-service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifications.rule=PathPrefix(`/ws`)"
      - "traefik.http.services.notifications.loadbalancer.server.port=4000"
    networks: [usewa-net]

  web:
    build:
      context: ../apps/web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=5173"
    networks: [usewa-net]

volumes:
  pgdata:

networks:
  usewa-net:
    driver: bridge
